// large-app-vite/src/components/DataGridComponent.jsx
// import React, { useState, useEffect } from "react";
// import { DataGrid } from "@mui/x-data-grid";
// import { Button } from "@mui/material";
// import * as api from "../services/api";

// const DataGridComponent = ({ entity }) => {
//   const getInitialPage = (entity) => {
//     return entity === "Products" ? 3 : 1; // Start at page 3 for Products
//   };

//   const [data, setData] = useState([]);
//   const [page, setPage] = useState(getInitialPage(entity));
//   const [loading, setLoading] = useState(false);
//   const [error, setError] = useState(null);

//   const pageSize = 1000;

//   const columns = {
//     Products: [
//       { field: "id", headerName: "ID", width: 90 },
//       { field: "productName", headerName: "Product Name", width: 150 },
//       { field: "category", headerName: "Category", width: 150 },
//       { field: "price", headerName: "Price", width: 120 },
//     ],
//     Orders: [
//       { field: "id", headerName: "ID", width: 90 },
//       { field: "orderDate", headerName: "Order Date", width: 150 },
//       { field: "customerId", headerName: "Customer ID", width: 120 },
//       { field: "totalAmount", headerName: "Total Amount", width: 120 },
//     ],
//     Customers: [
//       { field: "id", headerName: "ID", width: 90 },
//       { field: "firstName", headerName: "First Name", width: 150 },
//       { field: "lastName", headerName: "Last Name", width: 150 },
//       { field: "email", headerName: "Email", width: 200 },
//     ],
//     Inventory: [
//       { field: "id", headerName: "ID", width: 90 },
//       { field: "productId", headerName: "Product ID", width: 120 },
//       { field: "warehouseId", headerName: "Warehouse ID", width: 120 },
//       { field: "quantity", headerName: "Quantity", width: 120 },
//     ],
//     Suppliers: [
//       { field: "id", headerName: "ID", width: 90 },
//       { field: "companyName", headerName: "Company Name", width: 150 },
//       { field: "contactName", headerName: "Contact Name", width: 150 },
//       { field: "email", headerName: "Email", width: 200 },
//     ],
//   };

//   const getPageRange = (entity) => {
//     switch (entity) {
//       case "Products":
//         return { min: 2, max: 5 };
//       case "Customers":
//         return { min: 1, max: 13 };
//       case "Inventory":
//         return { min: 1, max: 15 };
//       case "Suppliers":
//         return { min: 1, max: 10 };
//       default:
//         return { min: 1, max: 1 }; // Orders doesn't use pagination
//     }
//   };

//   const fetchData = async () => {
//     setLoading(true);
//     setError(null);
//     try {
//       let result;
//       switch (entity) {
//         case "Products":
//           result = await api.getProducts(page);
//           break;
//         case "Orders":
//           result = await api.getOrders();
//           break;
//         case "Customers":
//           result = await api.getCustomers(page);
//           break;
//         case "Inventory":
//           result = await api.getInventory(page);
//           break;
//         case "Suppliers":
//           result = await api.getSuppliers(page);
//           break;
//         default:
//           throw new Error("Invalid entity");
//       }
//       setData(result);
//     } catch (err) {
//       setError(
//         `Failed to fetch ${entity}: ${err.message} (Status: ${err.response?.status})`
//       );
//     } finally {
//       setLoading(false);
//     }
//   };

//   useEffect(() => {
//     fetchData();
//   }, [page, entity]);

//   useEffect(() => {
//     setPage(getInitialPage(entity));
//   }, [entity]);

//   const { min: minPage, max: maxPage } = getPageRange(entity);

//   return (
//     <div style={{ height: 600, width: "100%" }}>
//       {error && <div style={{ color: "red" }}>{error}</div>}
//       {loading ? (
//         <div>Loading...</div>
//       ) : (
//         <>
//           <DataGrid
//             rows={data}
//             columns={columns[entity]}
//             pageSize={pageSize}
//             rowsPerPageOptions={[pageSize]}
//             pagination
//             disableSelectionOnClick
//           />
//           {entity !== "Orders" && (
//             <div>
//               <Button
//                 onClick={() => setPage(page - 1)}
//                 disabled={page <= minPage}
//               >
//                 Previous
//               </Button>
//               <Button
//                 onClick={() => setPage(page + 1)}
//                 disabled={page >= maxPage || data.length < pageSize}
//               >
//                 Next
//               </Button>
//               <span>
//                 {" "}
//                 Page {page} of {maxPage}{" "}
//               </span>
//             </div>
//           )}
//         </>
//       )}
//     </div>
//   );
// };

// export default DataGridComponent;


import React, { useState, useEffect } from "react";
import { DataGrid } from "@mui/x-data-grid";
import { Button } from "@mui/material";
import * as api from "../services/api";

const DataGridComponent = ({ entity }) => {
  const getInitialPage = (entity) => {
    return entity === "Products" ? 3 : 1; // Start at page 3 for Products
  };

  const [data, setData] = useState([]);
  const [page, setPage] = useState(getInitialPage(entity));
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const pageSize = 1000;

  const columns = {
    Products: [
      { field: "id", headerName: "ID", width: 90 },
      { field: "productName", headerName: "Product Name", width: 150 },
      { field: "category", headerName: "Category", width: 150 },
      { field: "price", headerName: "Price", width: 120 },
      { field: "stock", headerName: "Stock", width: 100 },
      { field: "createdDate", headerName: "Created Date", width: 150 },
      { field: "lastUpdated", headerName: "Last Updated", width: 150 },
      { field: "description", headerName: "Description", width: 200 },
      // { field: "manufacturer", headerName: "Manufacturer", width: 150 },
      // { field: "sku", headerName: "SKU", width: 120 },
      // { field: "weight", headerName: "Weight", width: 100 },
      // { field: "dimensions", headerName: "Dimensions", width: 150 },
      // { field: "color", headerName: "Color", width: 120 },
      // { field: "material", headerName: "Material", width: 120 },
      // { field: "warrantyMonths", headerName: "Warranty Months", width: 120 },
      // { field: "isActive", headerName: "Is Active", width: 100 },
      // { field: "rating", headerName: "Rating", width: 100 },
      { field: "discount", headerName: "Discount", width: 100 },
      { field: "supplierId", headerName: "Supplier ID", width: 100 },
      { field: "batchNumber", headerName: "Batch Number", width: 120 },
      { field: "expiryDate", headerName: "Expiry Date", width: 150 },
      { field: "countryOfOrigin", headerName: "Country of Origin", width: 150 },
      { field: "isFeatured", headerName: "Is Featured", width: 100 },
      {
        field: "maxOrderQuantity",
        headerName: "Max Order Quantity",
        width: 120,
      },
      { field: "leadTimeDays", headerName: "Lead Time Days", width: 120 },
    ],
    Orders: [
      { field: "id", headerName: "ID", width: 90 },
      { field: "orderDate", headerName: "Order Date", width: 150 },
      { field: "customerId", headerName: "Customer ID", width: 120 },
      { field: "totalAmount", headerName: "Total Amount", width: 120 },
      { field: "status", headerName: "Status", width: 120 },
      { field: "shippingAddress", headerName: "Shipping Address", width: 200 },
      { field: "billingAddress", headerName: "Billing Address", width: 200 },
      { field: "paymentMethod", headerName: "Payment Method", width: 150 },
      { field: "orderNumber", headerName: "Order Number", width: 120 },
      {
        field: "expectedDelivery",
        headerName: "Expected Delivery",
        width: 150,
      },
      { field: "actualDelivery", headerName: "Actual Delivery", width: 150 },
      { field: "isDelivered", headerName: "Is Delivered", width: 100 },
      { field: "taxAmount", headerName: "Tax Amount", width: 120 },
      { field: "discountAmount", headerName: "Discount Amount", width: 120 },
      { field: "shippingCost", headerName: "Shipping Cost", width: 120 },
      { field: "orderNotes", headerName: "Order Notes", width: 200 },
      { field: "createdBy", headerName: "Created By", width: 150 },
      { field: "modifiedBy", headerName: "Modified By", width: 150 },
      { field: "createdDate", headerName: "Created Date", width: 150 },
      { field: "modifiedDate", headerName: "Modified Date", width: 150 },
      { field: "customerEmail", headerName: "Customer Email", width: 200 },
      { field: "customerPhone", headerName: "Customer Phone", width: 150 },
      { field: "orderPriority", headerName: "Order Priority", width: 120 },
      { field: "shippingMethod", headerName: "Shipping Method", width: 150 },
      { field: "trackingNumber", headerName: "Tracking Number", width: 150 },
      { field: "couponCode", headerName: "Coupon Code", width: 120 },
      { field: "isGift", headerName: "Is Gift", width: 100 },
      { field: "giftMessage", headerName: "Gift Message", width: 200 },
      { field: "salesChannel", headerName: "Sales Channel", width: 150 },
      { field: "orderWeight", headerName: "Order Weight", width: 120 },
    ],
    Customers: [
      { field: "id", headerName: "ID", width: 90 },
      { field: "firstName", headerName: "First Name", width: 150 },
      { field: "lastName", headerName: "Last Name", width: 150 },
      { field: "email", headerName: "Email", width: 200 },
      { field: "phone", headerName: "Phone", width: 150 },
      { field: "addressLine1", headerName: "Address Line 1", width: 200 },
      { field: "addressLine2", headerName: "Address Line 2", width: 200 },
      { field: "city", headerName: "City", width: 120 },
      { field: "state", headerName: "State", width: 120 },
      { field: "zipCode", headerName: "Zip Code", width: 120 },
      { field: "country", headerName: "Country", width: 120 },
      { field: "createdDate", headerName: "Created Date", width: 150 },
      { field: "lastUpdated", headerName: "Last Updated", width: 150 },
      { field: "isActive", headerName: "Is Active", width: 100 },
      { field: "dateOfBirth", headerName: "Date of Birth", width: 150 },
      { field: "gender", headerName: "Gender", width: 100 },
      { field: "occupation", headerName: "Occupation", width: 150 },
      { field: "companyName", headerName: "Company Name", width: 150 },
      { field: "annualIncome", headerName: "Annual Income", width: 120 },
      { field: "customerType", headerName: "Customer Type", width: 120 },
      { field: "loyaltyPoints", headerName: "Loyalty Points", width: 120 },
      {
        field: "lastPurchaseDate",
        headerName: "Last Purchase Date",
        width: 150,
      },
      {
        field: "newsletterSubscribed",
        headerName: "Newsletter Subscribed",
        width: 120,
      },
      {
        field: "preferredContactMethod",
        headerName: "Preferred Contact Method",
        width: 150,
      },
      { field: "accountStatus", headerName: "Account Status", width: 120 },
      { field: "creditLimit", headerName: "Credit Limit", width: 120 },
      { field: "billingAddress", headerName: "Billing Address", width: 200 },
      { field: "shippingAddress", headerName: "Shipping Address", width: 200 },
      { field: "taxId", headerName: "Tax ID", width: 120 },
      { field: "customerSegment", headerName: "Customer Segment", width: 120 },
      {
        field: "registrationDate",
        headerName: "Registration Date",
        width: 150,
      },
      { field: "lastLoginDate", headerName: "Last Login Date", width: 150 },
      {
        field: "preferredLanguage",
        headerName: "Preferred Language",
        width: 120,
      },
      { field: "timeZone", headerName: "Time Zone", width: 120 },
      { field: "notes", headerName: "Notes", width: 200 },
      {
        field: "emergencyContact",
        headerName: "Emergency Contact",
        width: 150,
      },
      { field: "emergencyPhone", headerName: "Emergency Phone", width: 150 },
      { field: "referralSource", headerName: "Referral Source", width: 150 },
      {
        field: "socialMediaHandle",
        headerName: "Social Media Handle",
        width: 150,
      },
      { field: "website", headerName: "Website", width: 200 },
      { field: "fax", headerName: "Fax", width: 120 },
      { field: "isVerified", headerName: "Is Verified", width: 100 },
      {
        field: "verificationDate",
        headerName: "Verification Date",
        width: 150,
      },
      { field: "lastContacted", headerName: "Last Contacted", width: 150 },
      { field: "customerRating", headerName: "Customer Rating", width: 120 },
    ],
    Inventory: [
      { field: "id", headerName: "ID", width: 90 },
      { field: "productId", headerName: "Product ID", width: 120 },
      { field: "warehouseId", headerName: "Warehouse ID", width: 120 },
      { field: "quantity", headerName: "Quantity", width: 120 },
      { field: "lastUpdated", headerName: "Last Updated", width: 150 },
      { field: "stockStatus", headerName: "Stock Status", width: 120 },
      { field: "reorderLevel", headerName: "Reorder Level", width: 120 },
      // { field: "reorderQuantity", headerName: "Reorder Quantity", width: 120 },
      // { field: "lastRestockDate", headerName: "Last Restock Date", width: 150 },
      // { field: "supplierId", headerName: "Supplier ID", width: 120 },
      // { field: "batchNumber", headerName: "Batch Number", width: 120 },
      // { field: "expiryDate", headerName: "Expiry Date", width: 150 },
      // { field: "storageLocation", headerName: "Storage Location", width: 150 },
      // { field: "unitCost", headerName: "Unit Cost", width: 120 },
      // { field: "totalCost", headerName: "Total Cost", width: 120 },
      // { field: "isDamaged", headerName: "Is Damaged", width: 100 },
      { field: "damageNotes", headerName: "Damage Notes", width: 200 },
      { field: "lastAuditDate", headerName: "Last Audit Date", width: 150 },
      { field: "auditStatus", headerName: "Audit Status", width: 120 },
      { field: "inventoryType", headerName: "Inventory Type", width: 120 },
    ],
    Suppliers: [
      { field: "id", headerName: "ID", width: 90 },
      { field: "companyName", headerName: "Company Name", width: 150 },
      { field: "contactName", headerName: "Contact Name", width: 150 },
      { field: "email", headerName: "Email", width: 200 },
      { field: "phone", headerName: "Phone", width: 150 },
      { field: "addressLine1", headerName: "Address Line 1", width: 200 },
      { field: "addressLine2", headerName: "Address Line 2", width: 200 },
      { field: "city", headerName: "City", width: 120 },
      { field: "state", headerName: "State", width: 120 },
      { field: "zipCode", headerName: "Zip Code", width: 120 },
      { field: "country", headerName: "Country", width: 120 },
      { field: "createdDate", headerName: "Created Date", width: 150 },
      { field: "lastUpdated", headerName: "Last Updated", width: 150 },
      { field: "isActive", headerName: "Is Active", width: 100 },
      { field: "supplierType", headerName: "Supplier Type", width: 120 },
      { field: "leadTimeDays", headerName: "Lead Time Days", width: 120 },
      {
        field: "minOrderQuantity",
        headerName: "Min Order Quantity",
        width: 120,
      },
      {
        field: "maxOrderQuantity",
        headerName: "Max Order Quantity",
        width: 120,
      },
      { field: "paymentTerms", headerName: "Payment Terms", width: 150 },
      { field: "taxId", headerName: "Tax ID", width: 120 },
      { field: "website", headerName: "Website", width: 200 },
      { field: "rating", headerName: "Rating", width: 100 },
      {
        field: "contractStartDate",
        headerName: "Contract Start Date",
        width: 150,
      },
      { field: "contractEndDate", headerName: "Contract End Date", width: 150 },
      { field: "notes", headerName: "Notes", width: 200 },
      // {
      //   field: "preferredContactMethod",
      //   headerName: "Preferred Contact Method",
      //   width: 150,
      // },
      // { field: "lastOrderDate", headerName: "Last Order Date", width: 150 },
      // {
      //   field: "supplierCategory",
      //   headerName: "Supplier Category",
      //   width: 150,
      // },
    ],
  };

  const getPageRange = (entity) => {
    switch (entity) {
      case "Products":
        return { min: 3, max: 5 };
      case "Customers":
        return { min: 1, max: 13 };
      case "Inventory":
        return { min: 1, max: 15 };
      case "Suppliers":
        return { min: 1, max: 10 };
      default:
        return { min: 1, max: 1 }; // Orders doesn't use pagination
    }
  };

  const fetchData = async () => {
    setLoading(true);
    setError(null);
    try {
      let result;
      switch (entity) {
        case "Products":
          result = await api.getProducts(page);
          break;
        case "Orders":
          result = await api.getOrders();
          break;
        case "Customers":
          result = await api.getCustomers(page);
          break;
        case "Inventory":
          result = await api.getInventory(page);
          break;
        case "Suppliers":
          result = await api.getSuppliers(page);
          break;
        default:
          throw new Error("Invalid entity");
      }
      setData(result);
    } catch (err) {
      setError(
        `Failed to fetch ${entity}: ${err.message} (Status: ${err.response?.status})`
      );
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, [page, entity]);

  useEffect(() => {
    setPage(getInitialPage(entity));
  }, [entity]);

  const { min: minPage, max: maxPage } = getPageRange(entity);

  return (
    <div style={{ height: 600, width: "100%" }}>
      {error && <div style={{ color: "red" }}>{error}</div>}
      {loading ? (
        <div>Loading...</div>
      ) : (
        <>
          <DataGrid
            rows={data}
            columns={columns[entity]}
            pageSize={pageSize}
            rowsPerPageOptions={[pageSize]}
            pagination
            disableSelectionOnClick
            autoHeight
            sx={{ overflowX: "auto" }}
          />
          {entity !== "Orders" && (
            <div>
              <Button
                onClick={() => setPage(page - 1)}
                disabled={page <= minPage}
              >
                Previous
              </Button>
              <Button
                onClick={() => setPage(page + 1)}
                disabled={page >= maxPage || data.length < pageSize}
              >
                Next
              </Button>
              <span>
                {" "}
                Page {page} of {maxPage}{" "}
              </span>
            </div>
          )}
        </>
      )}
    </div>
  );
};

export default DataGridComponent;

// large-scale-app-angular-ts/src/app/components/data-grid/data-grid.component.ts
import { Component, Input, OnInit, OnChanges, SimpleChanges } from '@angular/core';
import { MatTableDataSource } from '@angular/material/table';
import { MatPaginator, PageEvent } from '@angular/material/paginator';
import { MatTableModule } from '@angular/material/table';
import { MatPaginatorModule } from '@angular/material/paginator';
import { CommonModule } from '@angular/common'; // Added import for NgIf, NgFor, etc.
import { Observable } from 'rxjs';
import { ApiService } from '../../services/api.service';
import { ProductDto } from '../../models/product.model';
import { OrderDto } from '../../models/order.model';
import { CustomerDto } from '../../models/customer.model';
import { InventoryDto } from '../../models/inventory.model';
import { SupplierDto } from '../../models/supplier.model';

interface ColumnDef {
  field: string;
  headerName: string;
}

@Component({
  selector: 'app-data-grid',
  templateUrl: './data-grid.component.html',
  styleUrls: ['./data-grid.component.css'],
  standalone: true,
  imports: [MatTableModule, MatPaginatorModule, CommonModule] // Added CommonModule
})
export class DataGridComponent implements OnInit, OnChanges {
  @Input() entity: string = 'Products';
  dataSource = new MatTableDataSource<ProductDto | OrderDto | CustomerDto | InventoryDto | SupplierDto>([]);
  displayedColumns: string[] = [];
  columnDefs: ColumnDef[] = [];
  pageSize = 1000;
  currentPage = 1;
  totalRows = 0;
  minPage = 1;
  maxPage = 1;
  loading = false;
  error: string | null = null;

  constructor(private apiService: ApiService) {}

  ngOnInit() {
    this.setInitialState();
    this.fetchData();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['entity']) {
      this.setInitialState();
      this.fetchData();
    }
  }

  setInitialState() {
    this.currentPage = this.entity === 'Products' ? 3 : 1;
    this.error = null;
    this.loading = false;

    switch (this.entity) {
      case 'Products':
        this.minPage = 3;
        this.maxPage = 5;
        this.totalRows = 3000;
        this.columnDefs = [
          { field: 'id', headerName: 'ID' },
          { field: 'productName', headerName: 'Product Name' },
          { field: 'category', headerName: 'Category' },
          { field: 'price', headerName: 'Price' },
          { field: 'stock', headerName: 'Stock' },
          { field: 'createdDate', headerName: 'Created Date' },
          { field: 'lastUpdated', headerName: 'Last Updated' },
          { field: 'description', headerName: 'Description' },
          { field: 'discount', headerName: 'Discount' },
          { field: 'supplierId', headerName: 'Supplier ID' },
          { field: 'batchNumber', headerName: 'Batch Number' },
          { field: 'expiryDate', headerName: 'Expiry Date' },
          { field: 'countryOfOrigin', headerName: 'Country of Origin' },
          { field: 'isFeatured', headerName: 'Is Featured' },
          { field: 'maxOrderQuantity', headerName: 'Max Order Quantity' },
          { field: 'leadTimeDays', headerName: 'Lead Time Days' }
        ];
        break;
      case 'Orders':
        this.minPage = 1;
        this.maxPage = 1;
        this.totalRows = 600;
        this.columnDefs = [
          { field: 'id', headerName: 'ID' },
          { field: 'orderDate', headerName: 'Order Date' },
          { field: 'customerId', headerName: 'Customer ID' },
          { field: 'totalAmount', headerName: 'Total Amount' },
          { field: 'status', headerName: 'Status' },
          { field: 'shippingAddress', headerName: 'Shipping Address' },
          { field: 'billingAddress', headerName: 'Billing Address' },
          { field: 'paymentMethod', headerName: 'Payment Method' },
          { field: 'orderNumber', headerName: 'Order Number' },
          { field: 'expectedDelivery', headerName: 'Expected Delivery' },
          { field: 'actualDelivery', headerName: 'Actual Delivery' },
          { field: 'isDelivered', headerName: 'Is Delivered' },
          { field: 'taxAmount', headerName: 'Tax Amount' },
          { field: 'discountAmount', headerName: 'Discount Amount' },
          { field: 'shippingCost', headerName: 'Shipping Cost' },
          { field: 'orderNotes', headerName: 'Order Notes' },
          { field: 'createdBy', headerName: 'Created By' },
          { field: 'modifiedBy', headerName: 'Modified By' },
          { field: 'createdDate', headerName: 'Created Date' },
          { field: 'modifiedDate', headerName: 'Modified Date' },
          { field: 'customerEmail', headerName: 'Customer Email' },
          { field: 'customerPhone', headerName: 'Customer Phone' },
          { field: 'orderPriority', headerName: 'Order Priority' },
          { field: 'shippingMethod', headerName: 'Shipping Method' },
          { field: 'trackingNumber', headerName: 'Tracking Number' },
          { field: 'couponCode', headerName: 'Coupon Code' },
          { field: 'isGift', headerName: 'Is Gift' },
          { field: 'giftMessage', headerName: 'Gift Message' },
          { field: 'salesChannel', headerName: 'Sales Channel' },
          { field: 'orderWeight', headerName: 'Order Weight' }
        ];
        break;
      case 'Customers':
        this.minPage = 1;
        this.maxPage = 13;
        this.totalRows = 13000;
        this.columnDefs = [
          { field: 'id', headerName: 'ID' },
          { field: 'firstName', headerName: 'First Name' },
          { field: 'lastName', headerName: 'Last Name' },
          { field: 'email', headerName: 'Email' },
          { field: 'phone', headerName: 'Phone' },
          { field: 'addressLine1', headerName: 'Address Line 1' },
          { field: 'addressLine2', headerName: 'Address Line 2' },
          { field: 'city', headerName: 'City' },
          { field: 'state', headerName: 'State' },
          { field: 'zipCode', headerName: 'Zip Code' },
          { field: 'country', headerName: 'Country' },
          { field: 'createdDate', headerName: 'Created Date' },
          { field: 'lastUpdated', headerName: 'Last Updated' },
          { field: 'isActive', headerName: 'Is Active' },
          { field: 'dateOfBirth', headerName: 'Date of Birth' },
          { field: 'gender', headerName: 'Gender' },
          { field: 'occupation', headerName: 'Occupation' },
          { field: 'companyName', headerName: 'Company Name' },
          { field: 'annualIncome', headerName: 'Annual Income' },
          { field: 'customerType', headerName: 'Customer Type' },
          { field: 'loyaltyPoints', headerName: 'Loyalty Points' },
          { field: 'lastPurchaseDate', headerName: 'Last Purchase Date' },
          { field: 'newsletterSubscribed', headerName: 'Newsletter Subscribed' },
          { field: 'preferredContactMethod', headerName: 'Preferred Contact Method' },
          { field: 'accountStatus', headerName: 'Account Status' },
          { field: 'creditLimit', headerName: 'Credit Limit' },
          { field: 'billingAddress', headerName: 'Billing Address' },
          { field: 'shippingAddress', headerName: 'Shipping Address' },
          { field: 'taxId', headerName: 'Tax ID' },
          { field: 'customerSegment', headerName: 'Customer Segment' },
          { field: 'registrationDate', headerName: 'Registration Date' },
          { field: 'lastLoginDate', headerName: 'Last Login Date' },
          { field: 'preferredLanguage', headerName: 'Preferred Language' },
          { field: 'timeZone', headerName: 'Time Zone' },
          { field: 'notes', headerName: 'Notes' },
          { field: 'emergencyContact', headerName: 'Emergency Contact' },
          { field: 'emergencyPhone', headerName: 'Emergency Phone' },
          { field: 'referralSource', headerName: 'Referral Source' },
          { field: 'socialMediaHandle', headerName: 'Social Media Handle' },
          { field: 'website', headerName: 'Website' },
          { field: 'fax', headerName: 'Fax' },
          { field: 'isVerified', headerName: 'Is Verified' },
          { field: 'verificationDate', headerName: 'Verification Date' },
          { field: 'lastContacted', headerName: 'Last Contacted' },
          { field: 'customerRating', headerName: 'Customer Rating' }
        ];
        break;
      case 'Inventory':
        this.minPage = 1;
        this.maxPage = 15;
        this.totalRows = 15000;
        this.columnDefs = [
          { field: 'id', headerName: 'ID' },
          { field: 'productId', headerName: 'Product ID' },
          { field: 'warehouseId', headerName: 'Warehouse ID' },
          { field: 'quantity', headerName: 'Quantity' },
          { field: 'lastUpdated', headerName: 'Last Updated' },
          { field: 'stockStatus', headerName: 'Stock Status' },
          { field: 'reorderLevel', headerName: 'Reorder Level' },
          { field: 'damageNotes', headerName: 'Damage Notes' },
          { field: 'lastAuditDate', headerName: 'Last Audit Date' },
          { field: 'auditStatus', headerName: 'Audit Status' },
          { field: 'inventoryType', headerName: 'Inventory Type' }
        ];
        break;
      case 'Suppliers':
        this.minPage = 1;
        this.maxPage = 10;
        this.totalRows = 10000;
        this.columnDefs = [
          { field: 'id', headerName: 'ID' },
          { field: 'companyName', headerName: 'Company Name' },
          { field: 'contactName', headerName: 'Contact Name' },
          { field: 'email', headerName: 'Email' },
          { field: 'phone', headerName: 'Phone' },
          { field: 'addressLine1', headerName: 'Address Line 1' },
          { field: 'addressLine2', headerName: 'Address Line 2' },
          { field: 'city', headerName: 'City' },
          { field: 'state', headerName: 'State' },
          { field: 'zipCode', headerName: 'Zip Code' },
          { field: 'country', headerName: 'Country' },
          { field: 'createdDate', headerName: 'Created Date' },
          { field: 'lastUpdated', headerName: 'Last Updated' },
          { field: 'isActive', headerName: 'Is Active' },
          { field: 'supplierType', headerName: 'Supplier Type' },
          { field: 'leadTimeDays', headerName: 'Lead Time Days' },
          { field: 'minOrderQuantity', headerName: 'Min Order Quantity' },
          { field: 'maxOrderQuantity', headerName: 'Max Order Quantity' },
          { field: 'paymentTerms', headerName: 'Payment Terms' },
          { field: 'taxId', headerName: 'Tax ID' },
          { field: 'website', headerName: 'Website' },
          { field: 'rating', headerName: 'Rating' },
          { field: 'contractStartDate', headerName: 'Contract Start Date' },
          { field: 'contractEndDate', headerName: 'Contract End Date' },
          { field: 'notes', headerName: 'Notes' }
        ];
        break;
    }
    this.displayedColumns = this.columnDefs.map(col => col.field);
  }

  fetchData() {
    this.loading = true;
    this.error = null;

    let observable: Observable<ProductDto[] | OrderDto[] | CustomerDto[] | InventoryDto[] | SupplierDto[]>;
    switch (this.entity) {
      case 'Products':
        observable = this.apiService.getProducts(this.currentPage);
        break;
      case 'Orders':
        observable = this.apiService.getOrders();
        break;
      case 'Customers':
        observable = this.apiService.getCustomers(this.currentPage);
        break;
      case 'Inventory':
        observable = this.apiService.getInventory(this.currentPage);
        break;
      case 'Suppliers':
        observable = this.apiService.getSuppliers(this.currentPage);
        break;
      default:
        this.error = 'Invalid entity';
        this.loading = false;
        return;
    }

    observable.subscribe({
      next: (data: ProductDto[] | OrderDto[] | CustomerDto[] | InventoryDto[] | SupplierDto[]) => {
        this.dataSource.data = data;
        this.loading = false;
      },
      error: (err: any) => {
        this.error = `Failed to fetch ${this.entity}: ${err.message}`;
        this.loading = false;
      }
    });
  }

  onPageChange(event: PageEvent) {
    this.currentPage = event.pageIndex + 1;
    this.fetchData();
  }
}

<div class="grid-container">
  @if (error) {
    <div class="error">{{ error }}</div>
  }
  @if (loading) {
    <div class="loading">Loading...</div>
  }
  @if (!loading && !error) {
    <table mat-table [dataSource]="dataSource" class="mat-elevation-z8">
      <ng-container *ngFor="let col of columnDefs" [matColumnDef]="col.field">
        <th mat-header-cell *matHeaderCellDef>{{ col.headerName }}</th>
        <td mat-cell *matCellDef="let row">{{ row[col.field] }}</td>
      </ng-container>
      <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
      <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
    </table>
  }
  @if (entity !== 'Orders') {
    <mat-paginator
      [pageSize]="pageSize"
      [pageSizeOptions]="[pageSize]"
      [length]="totalRows"
      [pageIndex]="currentPage - 1"
      (page)="onPageChange($event)"
    ></mat-paginator>
  }
</div>
